server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proofpulse
    username: proofpulse
    password: proofpulse
  jackson:
    serialization:
      write-dates-as-timestamps: false
